/* Generated by AN DISI Unibo */ 
package it.unibo.obstacledemo;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Obstacledemo extends QActorMsgQueue{
	public MsgHandle_Obstacledemo(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
