/* Generated by AN DISI Unibo */ 
package it.unibo.conditioncontrol;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Conditioncontrol extends QActorMsgQueue{
	public MsgHandle_Conditioncontrol(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
