/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRobotCleaner;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhsonar extends AbstractEvhsonar { 
	public Evhsonar(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
