/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRobotCleaner;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhs2 extends AbstractEvhs2 { 
	public Evhs2(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
