/* Generated by AN DISI Unibo */ 
package it.unibo.clocksensor;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Clocksensor extends QActorMsgQueue{
	public MsgHandle_Clocksensor(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
