/* Generated by AN DISI Unibo */ 
package it.unibo.tempsensor;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Tempsensor extends QActorMsgQueue{
	public MsgHandle_Tempsensor(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
